[server]
identity = "ed25519"
address = "127.0.0.1:8888"

[storage]
path = "./db"
log_level = "error"
register_ttl = "30m"
max_message_size = 10240 # 10 kb
max_queue_size = 10_000 # maximum of 100 mb per session

[rate_limit]
enabled = true
time_window = "1m"
quota = 20
